import { Projects } from "./type";
import {
  BiLogoTypescript,
  BiLogoJavascript,
  BiLogoCss3,
  BiLogoHtml5,
  BiLogoRedux,
  BiLogoReact,
  BiLogoTailwindCss,
} from "react-icons/bi";
import {
  SiI18Next,
  SiNextdotjs,
  SiReactquery,
  SiMui,
  SiAxios,
} from "react-icons/si";
import ReactHookFromIcon from "@/components/ui/svgs/reactHookForm";
import FormikIcon from "@/components/ui/svgs/formik";
import Yup from "@/components/ui/svgs/yup";
export const PROJECTS: Projects = [
  {
    id: "1",
    title: "projects.STG.title",
    description: {
      main: "projects.STG.description.main",
      list: [
        "commonDescription.MUI",
        "projects.STG.description.list.i18n",
        "commonDescription.reactQuery",
        "commonDescription.axios",
        "commonDescription.formik",
        "commonDescription.pagination",
        "commonDescription.debounce",
        "projects.STG.description.list.casl",
        "commonDescription.toast",
        "commonDescription.persistFilterValues",
        "commonDescription.skeleton",
        "commonDescription.login",
        "projects.STG.description.list.charts",
      ],
    },
    owner: "projects.STG.owner",
    projectEstimateTime: "4",
    images: new Array(10).map((_, index) => `/assets/images/stg/${index}.jpg`),
    tools: [
      BiLogoReact,
      BiLogoJavascript,
      BiLogoTypescript,
      BiLogoRedux,
      SiReactquery,
      BiLogoHtml5,
      BiLogoCss3,
      SiMui,
      FormikIcon,
      Yup,
      SiI18Next,
      SiAxios,
    ],
    collaborators: [],
  },
  {
    id: "2",
    title: "realState.title",
    description: { main: "", list: [] },
    owner: "Yahya Darwish ",
    projectEstimateTime: "3",
    images: [],
    link: "https://real-estate-nqtj.onrender.com/",
    sourceCodeUrl: "https://github.com/HamzaSourani/real-estate-app",
    tools: [
      BiLogoReact,
      BiLogoTypescript,
      BiLogoJavascript,
      SiReactquery,
      BiLogoHtml5,
      BiLogoCss3,
      SiMui,
      SiI18Next,
      FormikIcon,
      Yup,
      SiAxios,
    ],
    collaborators: [],
  },
  {
    id: "3",
    title: "levantDashboard.title",
    description: { main: "", list: [] },
    owner: "Levant company",
    projectEstimateTime: "6",
    images: [],
    tools: [
      SiNextdotjs,
      BiLogoReact,
      BiLogoJavascript,
      BiLogoRedux,
      BiLogoHtml5,
      BiLogoCss3,
      BiLogoTailwindCss,
      FormikIcon,
      Yup,
      SiAxios,
    ],
    collaborators: [],
  },
  {
    id: "4",
    title: "uluTechDashboard.title",
    description: { main: "", list: [] },
    owner: "UluTech company",
    projectEstimateTime: "7",
    images: [],
    tools: [
      BiLogoReact,
      BiLogoTypescript,
      BiLogoJavascript,
      SiReactquery,
      BiLogoRedux,
      BiLogoHtml5,
      BiLogoCss3,
      SiMui,
      SiI18Next,
      ReactHookFromIcon,
      Yup,
      SiAxios,
    ],
    collaborators: [],
  },
  {
    id: "5",
    title: "uluTechLandingPage.title",
    description: { main: "", list: [] },
    owner: "UluTech company",
    projectEstimateTime: "3",
    images: [],
    link: "",
    tools: [
      BiLogoReact,
      BiLogoTypescript,
      BiLogoJavascript,
      SiReactquery,
      BiLogoHtml5,
      BiLogoCss3,
      SiMui,
      SiI18Next,
      ReactHookFromIcon,
      Yup,
      SiAxios,
    ],
    collaborators: [],
  },
  {
    id: "6",
    title: "tripper.title",
    description: { main: "", list: [] },
    owner: "personal",
    projectEstimateTime: "3",
    images: [],
    link: "",
    sourceCodeUrl: "https://github.com/HamzaSourani/Tripper-app",
    tools: [
      BiLogoReact,
      BiLogoTypescript,
      BiLogoJavascript,
      BiLogoRedux,
      BiLogoHtml5,
      BiLogoCss3,
      SiMui,
      SiAxios,
    ],
    collaborators: [],
  },
  {
    id: "7",
    title: "alLabeeb.title",
    description: { main: "", list: [] },
    owner: "Al labeeb",
    projectEstimateTime: "1",
    images: [],
    sourceCodeUrl: "https://github.com/HamzaSourani/hear-me",
    tools: [
      BiLogoReact,
      BiLogoJavascript,
      BiLogoRedux,
      BiLogoHtml5,
      BiLogoCss3,
      SiMui,
      SiAxios,
    ],
    collaborators: [],
  },
  {
    id: "8",
    title: "uno.title",
    description: { main: "", list: [] },
    owner: "personal",
    projectEstimateTime: "3",
    images: [],
    link: "https://mtg2000.github.io/uno/game",
    sourceCodeUrl: "https://github.com/MTG2000/uno",
    tools: [
      BiLogoReact,
      BiLogoTypescript,
      BiLogoJavascript,
      BiLogoRedux,
      BiLogoHtml5,
      BiLogoCss3,
      SiMui,
    ],
    collaborators: [],
  },
  {
    id: "9",
    title: "smartNavigation.title",
    description: { main: "", list: [] },
    owner: "MTG",
    projectEstimateTime: "2",
    images: [],
    link: "https://mtg2000.github.io/speech-commands/",
    sourceCodeUrl: "https://github.com/MTG2000/speech-commands",
    tools: [BiLogoReact, BiLogoJavascript, BiLogoHtml5, BiLogoCss3, SiMui],
    collaborators: [],
  },
  {
    id: "10",
    title: "levantApp.title",
    description: { main: "", list: [] },
    owner: "Levant company",
    projectEstimateTime: "6",
    images: [],
    tools: [
      SiNextdotjs,
      BiLogoJavascript,
      BiLogoHtml5,
      BiLogoCss3,
      BiLogoTailwindCss,
      FormikIcon,
      Yup,
    ],
    collaborators: [],
  },
];
