import { Projects } from "./type";
import {
  BiLogoTypescript,
  BiLogoJavascript,
  BiLogoCss3,
  BiLogoHtml5,
  BiLogoRedux,
  BiLogoReact,
  BiLogoTailwindCss,
} from "react-icons/bi";
import {
  SiI18Next,
  SiNextdotjs,
  SiReactquery,
  SiMui,
  SiAxios,
  SiReactrouter,
  SiReacthookform,
  SiXstate,
} from "react-icons/si";
import FormikIcon from "@/components/ui/svgs/formik";
import Yup from "@/components/ui/svgs/yup";
import ReactSuiteIcon from "@/components/ui/svgs/rSuite";
import ReactIconsIcon from "@/components/ui/svgs/reactIcons";
export const PROJECTS: Projects = [
  {
    id: "0",
    title: "projects.STG.title",
    description: {
      main: "projects.STG.description.main",
      list: [
        "commonDescription.MUI",
        "projects.STG.description.list.i18n",
        "commonDescription.reactQuery",
        "commonDescription.axios",
        "commonDescription.formik",
        "commonDescription.pagination",
        "commonDescription.debounce",
        "projects.STG.description.list.casl",
        "commonDescription.toast",
        "commonDescription.persistFilterValues",
        "commonDescription.skeleton",
        "commonDescription.login",
        "commonDescription.charts",
      ],
    },
    owner: "projects.STG.owner",
    estimateTime: "312",
    images: Array.from(
      { length: 10 },
      (_, index) => `/assets/images/stg/${index}.png`,
    ),
    tools: [
      { label: "react.js", icon: BiLogoReact },
      { label: "javascript", icon: BiLogoJavascript },
      { label: "typescript", icon: BiLogoTypescript },
      { label: "react router", icon: SiReactrouter },
      { label: "react query", icon: SiReactquery },
      { label: "redux", icon: BiLogoRedux },
      { label: "MUI", icon: SiMui },
      { label: "CSS", icon: BiLogoCss3 },
      { label: "HTML", icon: BiLogoHtml5 },
      { label: "i18next", icon: SiI18Next },
      { label: "formik", icon: FormikIcon },
      { label: "yup", icon: Yup },
      { label: "axios", icon: SiAxios },
    ],
    collaborators: [],
  },
  {
    id: "1",
    title: "projects.realEstate.title",
    description: {
      main: "projects.realEstate.description.main",
      list: [
        "commonDescription.MUI",
        "projects.realEstate.description.list.i18n",
        "commonDescription.reactQuery",
        "commonDescription.axios",
        "projects.realEstate.description.list.formik",
        "projects.realEstate.description.list.pagination",
        "commonDescription.toast",
        "commonDescription.skeleton",
        "commonDescription.auth",
        "commonDescription.guest",
      ],
    },
    owner: "projects.realEstate.owner ",
    estimateTime: "120",
    images: Array.from(
      { length: 21 },
      (_, index) => `/assets/images/realEstate/${index}.png`,
    ),
    link: "https://real-estate-nqtj.onrender.com/",
    sourceCodeUrl: "https://github.com/HamzaSourani/real-estate-app",
    tools: [
      { label: "react.js", icon: BiLogoReact },
      { label: "javascript", icon: BiLogoJavascript },
      { label: "typescript", icon: BiLogoTypescript },
      { label: "react router", icon: SiReactrouter },
      { label: "react query", icon: SiReactquery },
      { label: "MUI", icon: SiMui },
      { label: "CSS", icon: BiLogoCss3 },
      { label: "HTML", icon: BiLogoHtml5 },
      { label: "i18next", icon: SiI18Next },
      { label: "formik", icon: FormikIcon },
      { label: "yup", icon: Yup },
      { label: "axios", icon: SiAxios },
    ],
    collaborators: [],
  },
  {
    id: "2",
    title: "projects.addressDashboard.title",
    description: {
      main: "projects.addressDashboard.description.main",
      list: [
        "projects.addressDashboard.description.list.ui",
        "commonDescription.redux",
        "commonDescription.axios",
        "commonDescription.formik",
        "commonDescription.pagination",
        "commonDescription.debounce",
        "projects.addressDashboard.description.list.casl",
        "commonDescription.toast",
        "commonDescription.persistFilterValues",
        "commonDescription.login",
        "commonDescription.charts",
      ],
    },
    owner: "projects.addressDashboard.owner",
    estimateTime: "728",
    images: Array.from(
      { length: 14 },
      (_, index) => `/assets/images/addressDashboard/${index}.png`,
    ),

    tools: [
      { label: "react.js", icon: BiLogoReact },
      { label: "next.js", icon: SiNextdotjs },
      { label: "javascript", icon: BiLogoJavascript },
      { label: "typescript", icon: BiLogoTypescript },
      { label: "redux", icon: BiLogoRedux },
      { label: "tailwind", icon: BiLogoTailwindCss },
      { label: "react suite", icon: ReactSuiteIcon },
      { label: "CSS", icon: BiLogoCss3 },
      { label: "HTML", icon: BiLogoHtml5 },
      { label: "formik", icon: FormikIcon },
      { label: "react icons", icon: ReactIconsIcon },
      { label: "yup", icon: Yup },
      { label: "axios", icon: SiAxios },
    ],
    collaborators: [],
  },
  {
    id: "3",
    title: "projects.humyDashboard.title",
    description: {
      main: "projects.humyDashboard.description.main",
      list: [
        "commonDescription.MUI",
        "projects.humyDashboard.description.list.i18n",
        "commonDescription.reactQuery",
        "commonDescription.axios",
        "commonDescription.reactHookForm",
        "commonDescription.pagination",
        "commonDescription.debounce",
        "projects.humyDashboard.description.list.permission",
        "commonDescription.toast",
        "commonDescription.login",
      ],
    },
    owner: "projects.humyDashboard.owner",
    estimateTime: "840",
    images: Array.from(
      { length: 22 },
      (_, index) => `/assets/images/humyDashboard/${index}.png`,
    ),

    tools: [
      { label: "react.js", icon: BiLogoReact },
      { label: "javascript", icon: BiLogoJavascript },
      { label: "typescript", icon: BiLogoTypescript },
      { label: "react router", icon: SiReactrouter },
      { label: "react query", icon: SiReactquery },
      { label: "redux", icon: BiLogoRedux },
      { label: "MUI", icon: SiMui },
      { label: "CSS", icon: BiLogoCss3 },
      { label: "HTML", icon: BiLogoHtml5 },
      { label: "i18next", icon: SiI18Next },
      { label: "react hook form", icon: SiReacthookform },
      { label: "yup", icon: Yup },
      { label: "axios", icon: SiAxios },
    ],
    collaborators: [],
  },
  {
    id: "4",
    title: "projects.humyLandingPage.title",
    description: {
      main: "projects.humyLandingPage.description.main",
      list: [
        "commonDescription.MUI",
        "projects.humyLandingPage.description.list.i18n",
        "commonDescription.reactQuery",
        "commonDescription.axios",
        "commonDescription.reactHookForm",
        "commonDescription.toast",
      ],
    },
    owner: "projects.humyLandingPage.owner",
    estimateTime: "140",
    images: Array.from(
      { length: 7 },
      (_, index) => `/assets/images/humyLandingPage/${index}.png`,
    ),
    link: "https://humyapp.net",
    tools: [
      { label: "react.js", icon: BiLogoReact },
      { label: "javascript", icon: BiLogoJavascript },
      { label: "typescript", icon: BiLogoTypescript },
      { label: "react router", icon: SiReactrouter },
      { label: "react query", icon: SiReactquery },
      { label: "redux", icon: BiLogoRedux },
      { label: "MUI", icon: SiMui },
      { label: "CSS", icon: BiLogoCss3 },
      { label: "HTML", icon: BiLogoHtml5 },
      { label: "i18next", icon: SiI18Next },
      { label: "react hook form", icon: SiReacthookform },
      { label: "yup", icon: Yup },
      { label: "axios", icon: SiAxios },
    ],
    collaborators: [],
  },
  {
    id: "5",
    title: "projects.tripper.title",
    description: {
      main: "projects.tripper.description.main",
      list: [
        "commonDescription.MUI",
        "commonDescription.redux",
        "commonDescription.axios",
        "commonDescription.debounce",
        "commonDescription.auth",
      ],
    },
    owner: "projects.tripper.owner",
    estimateTime: "280",
    images: Array.from(
      { length: 7 },
      (_, index) => `/assets/images/tripper/${index}.png`,
    ),
    link: "",
    sourceCodeUrl: "https://github.com/HamzaSourani/Tripper-app",
    tools: [
      { label: "react.js", icon: BiLogoReact },
      { label: "javascript", icon: BiLogoJavascript },
      { label: "typescript", icon: BiLogoTypescript },
      { label: "react router", icon: SiReactrouter },
      { label: "redux", icon: BiLogoRedux },
      { label: "MUI", icon: SiMui },
      { label: "CSS", icon: BiLogoCss3 },
      { label: "HTML", icon: BiLogoHtml5 },
      { label: "axios", icon: SiAxios },
    ],
    collaborators: [],
  },
  {
    id: "6",
    title: "alLabeeb.title",
    description: { main: "", list: [] },
    owner: "Al labeeb",
    estimateTime: "1",
    images: [],
    sourceCodeUrl: "https://github.com/HamzaSourani/hear-me",
    tools: [
      { label: "react.js", icon: BiLogoReact },
      { label: "javascript", icon: BiLogoJavascript },
      { label: "react router", icon: SiReactrouter },
      { label: "redux", icon: BiLogoRedux },
      { label: "MUI", icon: SiMui },
      { label: "CSS", icon: BiLogoCss3 },
      { label: "HTML", icon: BiLogoHtml5 },
      { label: "i18next", icon: SiI18Next },
      { label: "axios", icon: SiAxios },
    ],
    collaborators: [],
  },

  {
    id: "7",
    title: "projects.smartNavigation.title",
    description: {
      main: "projects.smartNavigation.description.main",
      list: [],
    },
    owner: "projects.smartNavigation.owner",
    estimateTime: "50",
    images: Array.from(
      { length: 5 },
      (_, index) => `/assets/images/smartNavigation/${index}.png`,
    ),
    link: "https://mtg2000.github.io/speech-commands/",
    sourceCodeUrl: "https://github.com/MTG2000/speech-commands",
    tools: [
      { label: "react.js", icon: BiLogoReact },
      { label: "javascript", icon: BiLogoJavascript },
      { label: "react router", icon: SiReactrouter },
      { label: "Xstate", icon: SiXstate },
      { label: "MUI", icon: SiMui },
      { label: "CSS", icon: BiLogoCss3 },
      { label: "HTML", icon: BiLogoHtml5 },
    ],
    collaborators: [],
  },
  {
    id: "8",
    title: "levantApp.title",
    description: { main: "", list: [] },
    owner: "Levant company",
    estimateTime: "6",
    images: [],
    tools: [
      { label: "react.js", icon: BiLogoReact },
      { label: "next.js", icon: SiNextdotjs },
      { label: "javascript", icon: BiLogoJavascript },
      { label: "typescript", icon: BiLogoTypescript },
      { label: "tailwind", icon: BiLogoTailwindCss },
      { label: "CSS", icon: BiLogoCss3 },
      { label: "HTML", icon: BiLogoHtml5 },
      { label: "formik", icon: FormikIcon },
      { label: "yup", icon: Yup },
    ],
    collaborators: [],
  },
];
