import { Projects } from "./type";
import {
  BiLogoTypescript,
  BiLogoJavascript,
  BiLogoCss3,
  BiLogoHtml5,
  BiLogoRedux,
  BiLogoReact,
  BiLogoTailwindCss,
} from "react-icons/bi";
import {
  SiI18Next,
  SiNextdotjs,
  SiReactquery,
  SiMui,
  SiAxios,
} from "react-icons/si";
import ReactHookFromIcon from "@/components/ui/svgs/reactHookForm";
import FormikIcon from "@/components/ui/svgs/formik";
import Yup from "@/components/ui/svgs/yup";
export const PROJECTS: Projects = [
  {
    id: "0",
    title: "projects.STG.title",
    description: {
      main: "projects.STG.description.main",
      list: [
        "commonDescription.MUI",
        "projects.STG.description.list.i18n",
        "commonDescription.reactQuery",
        "commonDescription.axios",
        "commonDescription.formik",
        "commonDescription.pagination",
        "commonDescription.debounce",
        "projects.STG.description.list.casl",
        "commonDescription.toast",
        "commonDescription.persistFilterValues",
        "commonDescription.skeleton",
        "commonDescription.login",
        "projects.STG.description.list.charts",
      ],
    },
    owner: "projects.STG.owner",
    estimateTime: "312",
    images: Array.from(
      { length: 10 },
      (_, index) => `/assets/images/stg/${index}.png`,
    ),
    tools: [
      { label: "react.js", icon: BiLogoReact },
      { label: "javascript", icon: BiLogoJavascript },
      { label: "typescript", icon: BiLogoTypescript },
      { label: "react query", icon: SiReactquery },
      { label: "redux", icon: BiLogoRedux },
      { label: "MUI", icon: SiMui },
      { label: "CSS", icon: BiLogoCss3 },
      { label: "HTML", icon: BiLogoHtml5 },
      { label: "i18next", icon: SiI18Next },
      { label: "formik", icon: FormikIcon },
      { label: "yup", icon: Yup },
      { label: "axios", icon: SiAxios },
    ],
    collaborators: [],
  },
  {
    id: "1",
    title: "projects.realEstate.title",
    description: {
      main: "projects.realEstate.description.main",
      list: [
        "commonDescription.MUI",
        "projects.realEstate.description.list.i18n",
        "commonDescription.reactQuery",
        "commonDescription.axios",
        "projects.realEstate.description.list.formik",
        "projects.realEstate.description.list.pagination",
        "commonDescription.toast",
        "commonDescription.skeleton",
        "commonDescription.auth",
        "commonDescription.guest",
      ],
    },
    owner: "projects.realEstate.owner ",
    estimateTime: "120",
    images: Array.from(
      { length: 21 },
      (_, index) => `/assets/images/realEstate/${index}.png`,
    ),
    link: "https://real-estate-nqtj.onrender.com/",
    sourceCodeUrl: "https://github.com/HamzaSourani/real-estate-app",
    tools: [
      { label: "react.js", icon: BiLogoReact },
      { label: "javascript", icon: BiLogoJavascript },
      { label: "typescript", icon: BiLogoTypescript },
      { label: "react query", icon: SiReactquery },
      { label: "MUI", icon: SiMui },
      { label: "CSS", icon: BiLogoCss3 },
      { label: "HTML", icon: BiLogoHtml5 },
      { label: "i18next", icon: SiI18Next },
      { label: "formik", icon: FormikIcon },
      { label: "yup", icon: Yup },
      { label: "axios", icon: SiAxios },
    ],
    collaborators: [],
  },
  {
    id: "2",
    title: "levantDashboard.title",
    description: { main: "projects.STG.description.main", list: [] },
    owner: "Levant company",
    estimateTime: "6",
    images: ["/assets/images/stg/2.png"],

    tools: [
      { label: "react.js", icon: BiLogoReact },
      { label: "next.js", icon: SiNextdotjs },
      { label: "javascript", icon: BiLogoJavascript },
      { label: "typescript", icon: BiLogoTypescript },
      { label: "redux", icon: BiLogoRedux },
      { label: "tailwind", icon: BiLogoTailwindCss },
      { label: "CSS", icon: BiLogoCss3 },
      { label: "HTML", icon: BiLogoHtml5 },
      { label: "formik", icon: FormikIcon },
      { label: "yup", icon: Yup },
      { label: "axios", icon: SiAxios },
    ],
    collaborators: [],
  },
  {
    id: "3",
    title: "uluTechDashboard.title",
    description: { main: "projects.STG.description.main", list: [] },
    owner: "UluTech company",
    estimateTime: "7",
    images: ["/assets/images/stg/2.png"],

    tools: [
      { label: "react.js", icon: BiLogoReact },
      { label: "javascript", icon: BiLogoJavascript },
      { label: "typescript", icon: BiLogoTypescript },
      { label: "react query", icon: SiReactquery },
      { label: "redux", icon: BiLogoRedux },
      { label: "MUI", icon: SiMui },
      { label: "CSS", icon: BiLogoCss3 },
      { label: "HTML", icon: BiLogoHtml5 },
      { label: "i18next", icon: SiI18Next },
      { label: "react hook form", icon: ReactHookFromIcon },
      { label: "yup", icon: Yup },
      { label: "axios", icon: SiAxios },
    ],
    collaborators: [],
  },
  {
    id: "4",
    title: "uluTechLandingPage.title",
    description: { main: "", list: [] },
    owner: "UluTech company",
    estimateTime: "3",
    images: [],
    link: "",
    tools: [
      { label: "react.js", icon: BiLogoReact },
      { label: "javascript", icon: BiLogoJavascript },
      { label: "typescript", icon: BiLogoTypescript },
      { label: "react query", icon: SiReactquery },
      { label: "redux", icon: BiLogoRedux },
      { label: "MUI", icon: SiMui },
      { label: "CSS", icon: BiLogoCss3 },
      { label: "HTML", icon: BiLogoHtml5 },
      { label: "i18next", icon: SiI18Next },
      { label: "react hook form", icon: ReactHookFromIcon },
      { label: "yup", icon: Yup },
      { label: "axios", icon: SiAxios },
    ],
    collaborators: [],
  },
  {
    id: "5",
    title: "tripper.title",
    description: { main: "", list: [] },
    owner: "personal",
    estimateTime: "3",
    images: [],
    link: "",
    sourceCodeUrl: "https://github.com/HamzaSourani/Tripper-app",
    tools: [
      { label: "react.js", icon: BiLogoReact },
      { label: "javascript", icon: BiLogoJavascript },
      { label: "typescript", icon: BiLogoTypescript },
      { label: "redux", icon: BiLogoRedux },
      { label: "MUI", icon: SiMui },
      { label: "CSS", icon: BiLogoCss3 },
      { label: "HTML", icon: BiLogoHtml5 },
      { label: "axios", icon: SiAxios },
    ],
    collaborators: [],
  },
  {
    id: "6",
    title: "alLabeeb.title",
    description: { main: "", list: [] },
    owner: "Al labeeb",
    estimateTime: "1",
    images: [],
    sourceCodeUrl: "https://github.com/HamzaSourani/hear-me",
    tools: [
      { label: "react.js", icon: BiLogoReact },
      { label: "javascript", icon: BiLogoJavascript },
      { label: "redux", icon: BiLogoRedux },
      { label: "MUI", icon: SiMui },
      { label: "CSS", icon: BiLogoCss3 },
      { label: "HTML", icon: BiLogoHtml5 },
      { label: "i18next", icon: SiI18Next },
      { label: "axios", icon: SiAxios },
    ],
    collaborators: [],
  },
  {
    id: "7",
    title: "uno.title",
    description: { main: "", list: [] },
    owner: "personal",
    estimateTime: "3",
    images: [],
    link: "https://mtg2000.github.io/uno/game",
    sourceCodeUrl: "https://github.com/MTG2000/uno",
    tools: [
      { label: "react.js", icon: BiLogoReact },
      { label: "javascript", icon: BiLogoJavascript },
      { label: "typescript", icon: BiLogoTypescript },
      { label: "redux", icon: BiLogoRedux },
      { label: "MUI", icon: SiMui },
      { label: "CSS", icon: BiLogoCss3 },
      { label: "HTML", icon: BiLogoHtml5 },
    ],
    collaborators: [],
  },
  {
    id: "8",
    title: "smartNavigation.title",
    description: { main: "", list: [] },
    owner: "personal",
    estimateTime: "2",
    images: [],
    link: "https://mtg2000.github.io/speech-commands/",
    sourceCodeUrl: "https://github.com/MTG2000/speech-commands",
    tools: [
      { label: "react.js", icon: BiLogoReact },
      { label: "javascript", icon: BiLogoJavascript },
      { label: "MUI", icon: SiMui },
      { label: "CSS", icon: BiLogoCss3 },
      { label: "HTML", icon: BiLogoHtml5 },
      BiLogoReact,
      BiLogoJavascript,
      BiLogoHtml5,
      BiLogoCss3,
      SiMui,
    ],
    collaborators: [],
  },
  {
    id: "9",
    title: "levantApp.title",
    description: { main: "", list: [] },
    owner: "Levant company",
    estimateTime: "6",
    images: [],
    tools: [
      { label: "react.js", icon: BiLogoReact },
      { label: "next.js", icon: SiNextdotjs },
      { label: "javascript", icon: BiLogoJavascript },
      { label: "typescript", icon: BiLogoTypescript },
      { label: "tailwind", icon: BiLogoTailwindCss },
      { label: "CSS", icon: BiLogoCss3 },
      { label: "HTML", icon: BiLogoHtml5 },
      { label: "formik", icon: FormikIcon },
      { label: "yup", icon: Yup },
    ],
    collaborators: [],
  },
];
